# -*- coding: utf-8 -*-
#
# This file is part of CERNServiceXML
# Copyright (C) 2015 CERN.
#
# CERNServiceXML is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=latest
  - REQUIREMENTS=devel

cache:
  - pip

install:
  # Install test dependencies
  - "travis_retry pip install coveralls pep257 Sphinx httpretty"
  - "travis_retry pip install pytest pytest-pep8 pytest-cov pytest-cache"
  - "if test -e requirements.${REQUIREMENTS}.${TRAVIS_PYTHON_VERSION}.txt; then REQ=${REQUIREMENTS}.${TRAVIS_PYTHON_VERSION}; else REQ=${REQUIREMENTS}; fi;"
  - "travis_retry pip install -r requirements.${REQ}.txt"
  - "travis_retry pip install -e ."

script:
  - pep257 cernservicexml
  - "sphinx-build -qnNW docs docs/_build/html"
  - python setup.py test
  - "sphinx-build -qnNW -b doctest docs docs/_build/doctest"

after_success:
  - coveralls

notifications:
  email: false

deploy:
  provider: pypi
  user: lnielsen
  password:
    secure: OO7o5i5aF1UEPOpq0uU4ObNwcQs+btzVMcaQJh0g5P4JDyMbgj8fLKi7u0eQDq3SITlVf3y05KTEqsLwq4emmEwlHUq5gjmBPv+F/8VXjZiYEIq+nqztBDdw1k2wD8cj/xV2RPAmjheFUmSb5/vFf/TY7Ifb9f5zZ1CsLeIhjrwQrXmhOeCGhgMS76S3br1339xJ67L/IW3nLyt62/1nV9eLBCcBrzEZJiDJnn1UdloPKAt23e31AQs04WT5Cw0gNPv3z8QqinbiuOAAMjoAP/hoTdSbt1cTBGYoc9QMJVn14vDWPYfc2K/3KCCo8gUrbHXAVmkUIeI/5tHMGauKPb+vdoq77VrK1X96mRucRAUv6UnbuE0MLOeLl3XcSVpq6IRz3n4jox41LJtuTNMQ2qUriHKaWzp4+k8tpLpmLqrI3lLUJBQLRmnrpXFt4JBoMcZBnYpGYS88+zdWOEmccVTrjgQ4shxkYfZQ6fAaLDFt5toJNYcFfKE5L12WywypXrTLNCpKMz6DeyVlsqG2K0mJJLABDYhaUEyh8zCiNgDXhFlKf3DrqoICQv4G4Z7g8DMZE/w9SBnintlrvLIOnsAq/zo8pkG3LxHCb7uWJOfCBwzFgG0xtstOH06xWqNGAfIH8aLzFqVP38BY4FJCa65blU87B1p6PRlnvoGIAmA=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $REQUIREMENTS = latest
